export const LOGIN = 'LOGIN';
export const GET_PRODUCT = 'GET_PRODUCT';
export const HANDLE_MODAL_CONFIRM_DELETE = 'HANDLE_MODAL_CONFIRM_DELETE';
export const HANDLE_MODAL_EDIT_PRODUCT = 'HANDLE_MODAL_EDIT_PRODUCT';